keys:
  - &thinkpad age1xs7ywlypc8kznrcnxweycy5vdc463jxqsk848z5n2s7ha6g7k5mq6h5ege
  - &thinkpad-system age1lwkf6utnzs5yftqtjdmffjvwtctfwj95ex9x6mjytgyasj7z394st3yh2r

  - &workstation age1hyda8g30kemzsggh8nyfmk2zlshvq2qvmtze9qv80js5xyhl0eqqcckk9x
  - &workstation-system age1z005zeuaj30gmw735emtzk7mm0zxp4j3q6syc74e45hefukupe7qf5nnke
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *thinkpad
      - *thinkpad-system
      - *workstation
      - *workstation-system
